Repository polypheny/Polypheny-DB, pull requests merged in 2020-01, with the labels that each got.

#154 Remove old entries in query analyzer
  catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/TransactionHandler.java
  catalog/src/main/java/ch/unibas/dmi/dbis/polyphenydb/catalog/XATransactionHandler.java
  config/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/ConfigServer.java
  config/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/ConfigWebsocket.java
  core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/enumerable/EnumerableInterpretable.java
  core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/runtime/ResultSetEnumerable.java
  core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/dialect/JethroDataSqlDialect.java
  core/src/test/java/ch/unibas/dmi/dbis/polyphenydb/test/concurrent/ConcurrentTestCommandScript.java
  dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/AbstractQueryProcessor.java
  dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/SqlProcessorImpl.java
  druid-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/druid/DruidDateTimeUtils.java
  geode-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/rel/GeodeTable.java
  geode-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/util/GeodeUtils.java
  geode-adapter/src/test/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/rel/RelationalJdbcExample.java
  geode-adapter/src/test/java/ch/unibas/dmi/dbis/polyphenydb/adapter/geode/simple/SimpleJdbcExample.java
  information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationManager.java
  information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationTable.java
  information/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/InformationWebSocket.java
  information/src/test/java/ch/unibas/dmi/dbis/polyphenydb/information/InformationManagerTest.java
  jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/AbstractJdbcStore.java
  jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/HsqldbStore.java
  jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/PostgresqlStore.java
  jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsMeta.java
  jdbc-interface/src/main/java/ch/unibas/dmi/dbis/polyphenydb/jdbc/DbmsService.java
  webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/Crud.java
Labels: A-im, C-cleanup, C-enhancement

#158 Fix query plan builder
  csv-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/csv/CsvStore.java
  dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/AbstractQueryProcessor.java
  dbms/src/main/java/ch/unibas/dmi/dbis/polyphenydb/processing/TransactionImpl.java
  webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/Crud.java
  webui/src/main/java/ch/unibas/dmi/dbis/polyphenydb/webui/models/Result.java
Labels: A-core, S-waiting-on-review

#165 Add support for MonetDB using the JDBC adapter
  core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/SqlDialect.java
  core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/sql/dialect/MonetdbSqlDialect.java
  dbms/build.gradle
  gradle.properties
  jdbc-adapter/build.gradle
  jdbc-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/jdbc/stores/MonetdbStore.java
Labels: A-stores, C-enhancement

#155 Basic implementation of Cassandra adapter
  cassandra-adapter/build.gradle
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraConvention.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraEnumerable.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraEnumerator.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraFilter.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraLimit.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraMetaDataProvider.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraMethod.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraPhysicalNameProvider.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraProject.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraRel.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraSchema.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraSort.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraStore.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraTable.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraTableModify.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraTableScan.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraToEnumerableConverter.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/CassandraValues.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraConverterRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraFilterRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraLimitRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraProjectRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraRules.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraSortRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraTableModificationRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraToEnumerableConverterRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/rules/CassandraValuesRule.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/util/CassandraTypesUtils.java
  cassandra-adapter/src/main/java/ch/unibas/dmi/dbis/polyphenydb/adapter/cassandra/util/CassandraUtils.java
  core/src/main/java/ch/unibas/dmi/dbis/polyphenydb/rel/externalize/RelJson.java
  dbms/build.gradle
  gradle.properties
Labels: A-stores, C-feature-accepted
